## Notebook 02: Data Preprocessing

### Import libraries

In [20]:
import pandas as pd
import numpy as np
import sys

In [21]:
# add src folder to path to use defined functions
sys.path.append('../src')
from preprocessing import map_team_names

### Load Raw CSV Files

In [22]:
mvp_shares = pd.read_csv('../data/raw/mvp_shares.csv')
player_stats = pd.read_csv('../data/raw/player_stats.csv')
team_stats = pd.read_csv('../data/raw/team_stats.csv')

### Look at Content/Dimensions of Dataframes

In [23]:
mvp_shares.info()
mvp_shares.describe()
mvp_shares.head()

<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 0 to 367
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           368 non-null    int64
 1   Rank                 368 non-null    str
 2   Player Name          368 non-null    str
 3   Team                 368 non-null    str
 4   First Place Votes    368 non-null    int64
 5   Total Voting Points  368 non-null    int64
 6   Voting_Pts Max       368 non-null    int64
 7   MVP Share            368 non-null    float64
 8   Season               368 non-null    int64
dtypes: float64(1), int64(5), str(3)
memory usage: 32.2 KB

,Unnamed: 0,Rank,Player Name,Team,First Place Votes,Total Voting Points,Voting_Pts Max,MVP Share,Season
0,0,1,Shaquille O'Neal,LAL,120,1207,1210,0.998,2000
1,1,2,Kevin Garnett,MIN,0,408,1210,0.337,2000
2,2,3,Alonzo Mourning,MIA,0,367,1210,0.303,2000
3,3,4,Karl Malone,UTA,0,312,1210,0.258,2000
4,4,5,Tim Duncan,SAS,0,248,1210,0.205,2000

In [24]:
player_stats.info()
player_stats.describe()
player_stats.head()

<class 'pandas.DataFrame'>
RangeIndex: 5457 entries, 0 to 5456
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5457 non-null   int64
 1   Season             5457 non-null   int64
 2   PLAYER_ID          5457 non-null   int64
 3   PLAYER_NAME        5457 non-null   str
 4   TEAM_ABBREVIATION  5457 non-null   str
 5   GP                 5457 non-null   int64
 6   W                  5457 non-null   int64
 7   L                  5457 non-null   int64
 8   MIN                5457 non-null   float64
 9   PTS                5457 non-null   int64
 10  REB                5457 non-null   int64
 11  AST                5457 non-null   int64
 12  STL                5457 non-null   int64
 13  BLK                5457 non-null   int64
 14  PTS_RANK           5457 non-null   int64
 15  REB_RANK           5457 non-null   int64
 16  AST_RANK           5457 non-null   int64
 17  PLUS_MINUS_RANK    5457 non-null   int64
 18  FG_PCT             5457 non-null   float64
 19  FG3_PCT            5457 non-null   float64
 20  FT_PCT             5457 non-null   float64
 21  PLUS_MINUS         5457 non-null   int64
dtypes: float64(4), int64(16), str(2)
memory usage: 1022.9 KB

,Unnamed: 0,Season,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,GP,W,L,MIN,PTS,...,STL,BLK,PTS_RANK,REB_RANK,AST_RANK,PLUS_MINUS_RANK,FG_PCT,FG3_PCT,FT_PCT,PLUS_MINUS
0,0,2000,920,A.C. Green,LAL,82,67,15,1930.201667,413,...,53,18,220,55,197,25,0.447,0.250,0.695,328
1,1,2000,243,Aaron McKie,PHI,82,49,33,1954.280000,653,...,108,18,139,179,70,125,0.411,0.364,0.829,52
2,2,2000,1502,Adonal Foyle,GSW,76,16,60,1652.911667,420,...,26,136,216,76,282,421,0.508,0.000,0.378,-349
3,3,2000,1559,Adrian Griffin,BOS,72,29,43,1928.203333,485,...,116,15,195,96,105,271,0.424,0.281,0.753,-31
4,4,2000,673,Alan Henderson,ATL,82,28,54,2779.498333,1083,...,81,54,60,35,201,424,0.461,0.100,0.671,-381

In [25]:
team_stats.info()
team_stats.describe()
team_stats.head()

<class 'pandas.DataFrame'>
RangeIndex: 805 entries, 0 to 804
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  805 non-null    int64
 1   Season      805 non-null    int64
 2   TEAM_ID     805 non-null    int64
 3   TEAM_NAME   805 non-null    str
 4   W           805 non-null    int64
 5   L           805 non-null    int64
 6   W_PCT       805 non-null    float64
 7   W_RANK      805 non-null    int64
 8   W_PCT_RANK  805 non-null    int64
dtypes: float64(1), int64(7), str(1)
memory usage: 69.3 KB

,Unnamed: 0,Season,TEAM_ID,TEAM_NAME,W,L,W_PCT,W_RANK,W_PCT_RANK
0,0,2000,1610612737,Atlanta Hawks,28,54,0.341,25,25
1,1,2000,1610612738,Boston Celtics,35,47,0.427,19,19
2,2,2000,1610612766,Charlotte Hornets,49,33,0.598,10,10
3,3,2000,1610612741,Chicago Bulls,17,65,0.207,28,28
4,4,2000,1610612739,Cleveland Cavaliers,32,50,0.390,22,22

## Part 1: Data Cleaning

### Convert Total Stats to Per Game Stats

In [26]:
player_stats['MIN'] = round(player_stats['MIN'] / player_stats['GP'], 1)
player_stats['PTS'] = round(player_stats['PTS'] / player_stats['GP'], 1)
player_stats['AST'] = round(player_stats['AST'] / player_stats['GP'], 1)
player_stats['REB'] = round(player_stats['REB'] / player_stats['GP'], 1)
player_stats['STL'] = round(player_stats['STL'] / player_stats['GP'], 1)
player_stats['BLK'] = round(player_stats['BLK'] / player_stats['GP'], 1)

### Map Team Abbreviations to Team Names

In [27]:
map_team_names(player_stats, team_stats)

In [28]:
# view result
player_stats.head()

,Unnamed: 0,Season,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,GP,W,L,MIN,PTS,...,BLK,PTS_RANK,REB_RANK,AST_RANK,PLUS_MINUS_RANK,FG_PCT,FG3_PCT,FT_PCT,PLUS_MINUS,TEAM_NAME
0,0,2000,920,A.C. Green,LAL,82,67,15,23.5,5.0,...,0.2,220,55,197,25,0.447,0.250,0.695,328,Los Angeles Lakers
1,1,2000,243,Aaron McKie,PHI,82,49,33,23.8,8.0,...,0.2,139,179,70,125,0.411,0.364,0.829,52,Philadelphia 76ers
2,2,2000,1502,Adonal Foyle,GSW,76,16,60,21.7,5.5,...,1.8,216,76,282,421,0.508,0.000,0.378,-349,Golden State Warriors
3,3,2000,1559,Adrian Griffin,BOS,72,29,43,26.8,6.7,...,0.2,195,96,105,271,0.424,0.281,0.753,-31,Boston Celtics
4,4,2000,673,Alan Henderson,ATL,82,28,54,33.9,13.2,...,0.7,60,35,201,424,0.461,0.100,0.671,-381,Atlanta Hawks

### Merge Dataframes

In [29]:
# merge player and team stats
player_team_stats = player_stats.merge(team_stats, on=['Season', 'TEAM_NAME'], how='left')

In [30]:
print(f"player_stats: {player_stats.shape}")
print(f"player_team_stats: {player_team_stats.shape}")

player_stats: (5457, 23)
player_team_stats: (5457, 30)

In [31]:
# rename player name col in mvp shares to match player_team stats
mvp_shares = mvp_shares.rename(columns={'Player Name': 'PLAYER_NAME'})

In [32]:
# find any name mismatches between bbr and nba_api
mvp_names = set(mvp_shares['PLAYER_NAME'].unique())
player_names = set(player_team_stats['PLAYER_NAME'].unique())

unmatched = mvp_names - player_names
print(unmatched)

for name in ['Dragic', 'Ginobili', 'Stojakovic', 'Butler']:
    matches = player_team_stats[player_team_stats['PLAYER_NAME'].str.contains(name)]
    print(matches['PLAYER_NAME'].unique())

# normalize names
player_name_normalized = {
    'Goran Dragić': 'Goran Dragic',
    'Manu Ginóbili': 'Manu Ginobili',
    'Peja Stojaković': 'Peja Stojakovic',
    'Jimmy Butler': 'Jimmy Butler III'
}

# apply mapping
mvp_shares['PLAYER_NAME'] = mvp_shares['PLAYER_NAME'].replace(player_name_normalized)

{'Jimmy Butler', 'Goran Dragić', 'Peja Stojaković', 'Manu Ginóbili'}
<ArrowStringArray>
['Goran Dragic']
Length: 1, dtype: str
<ArrowStringArray>
['Manu Ginobili']
Length: 1, dtype: str
<ArrowStringArray>
['Peja Stojakovic']
Length: 1, dtype: str
<ArrowStringArray>
['Caron Butler', 'Rasual Butler', 'Jimmy Butler III']
Length: 3, dtype: str

In [33]:
# confirm mapping was successful
unmatched = set(mvp_shares['PLAYER_NAME'].unique()) - set(player_team_stats['PLAYER_NAME'].unique())
print(unmatched)

set()

In [34]:
# merge mvp_shares with player_team_stats
merged_df = player_team_stats.merge(mvp_shares, on=['Season', 'PLAYER_NAME'], how='left')

print(merged_df.head())

   Unnamed: 0_x  Season  PLAYER_ID     PLAYER_NAME TEAM_ABBREVIATION  GP  W_x  \
0             0    2000        920      A.C. Green               LAL  82   67
1             1    2000        243     Aaron McKie               PHI  82   49
2             2    2000       1502    Adonal Foyle               GSW  76   16
3             3    2000       1559  Adrian Griffin               BOS  72   29
4             4    2000        673  Alan Henderson               ATL  82   28

   L_x   MIN   PTS  ...  W_PCT  W_RANK  W_PCT_RANK  Unnamed: 0  Rank  Team  \
0   15  23.5   5.0  ...  0.817       1           1         NaN   NaN   NaN
1   33  23.8   8.0  ...  0.598      10          10         NaN   NaN   NaN
2   60  21.7   5.5  ...  0.232      27          27         NaN   NaN   NaN
3   43  26.8   6.7  ...  0.427      19          19         NaN   NaN   NaN
4   54  33.9  13.2  ...  0.341      25          25         NaN   NaN   NaN

   First Place Votes  Total Voting Points  Voting_Pts Max  MVP Share
0                NaN                  NaN             NaN        NaN
1                NaN                  NaN             NaN        NaN
2                NaN                  NaN             NaN        NaN
3                NaN                  NaN             NaN        NaN
4                NaN                  NaN             NaN        NaN

[5 rows x 37 columns]

In [35]:
merged_df.columns

Index(['Unnamed: 0_x', 'Season', 'PLAYER_ID', 'PLAYER_NAME',
       'TEAM_ABBREVIATION', 'GP', 'W_x', 'L_x', 'MIN', 'PTS', 'REB', 'AST',
       'STL', 'BLK', 'PTS_RANK', 'REB_RANK', 'AST_RANK', 'PLUS_MINUS_RANK',
       'FG_PCT', 'FG3_PCT', 'FT_PCT', 'PLUS_MINUS', 'TEAM_NAME',
       'Unnamed: 0_y', 'TEAM_ID', 'W_y', 'L_y', 'W_PCT', 'W_RANK',
       'W_PCT_RANK', 'Unnamed: 0', 'Rank', 'Team', 'First Place Votes',
       'Total Voting Points', 'Voting_Pts Max', 'MVP Share'],
      dtype='str')

### Clean Merged Dataframe

In [36]:
# drop irrelevant cols
cols_to_drop = [
    'Unnamed: 0_x',   # index artifact
    'Unnamed: 0_y',   # index artifact
    'Unnamed: 0',     # index artifact
    'W_x',            # redundant with W_y
    'L_x',            # redundant with L_y
    'W_PCT_RANK',      # redundant with W_RANK
    'Rank',           # from mvp_shares, not a feature
    'Team',           # redundant with TEAM_NAME
    'TEAM_ABBREVIATION', # redundant with TEAM_NAME
    'First Place Votes',      # leakage - derived from MVP share
    'Total Voting Points',    # leakage - derived from MVP share
    'Voting_Pts Max',         # constant, not useful
]
merged_df = merged_df.drop(columns=cols_to_drop)

# rename cols for consistency and readability
merged_df = merged_df.rename(columns={'W_y': 'TEAM_W', 'L_y': 'TEAM_L', 'MVP Share': 'MVP_SHARE', 'Season': 'SEASON'})

# fill all NaNs in mvp share with 0s - these players recieved no mvp votes
merged_df['MVP_SHARE'] = merged_df['MVP_SHARE'].fillna(0)

In [37]:
# observe resulting dataframe
print(merged_df.shape)
print(merged_df.columns.tolist())
print(f"Non-zero MVP shares: {(merged_df['MVP_SHARE'] > 0).sum()}")
print(merged_df.isnull().sum())

(5457, 25)
['SEASON', 'PLAYER_ID', 'PLAYER_NAME', 'GP', 'MIN', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'PTS_RANK', 'REB_RANK', 'AST_RANK', 'PLUS_MINUS_RANK', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'PLUS_MINUS', 'TEAM_NAME', 'TEAM_ID', 'TEAM_W', 'TEAM_L', 'W_PCT', 'W_RANK', 'MVP_SHARE']
Non-zero MVP shares: 363
SEASON             0
PLAYER_ID          0
PLAYER_NAME        0
GP                 0
MIN                0
PTS                0
REB                0
AST                0
STL                0
BLK                0
PTS_RANK           0
REB_RANK           0
AST_RANK           0
PLUS_MINUS_RANK    0
FG_PCT             0
FG3_PCT            0
FT_PCT             0
PLUS_MINUS         0
TEAM_NAME          0
TEAM_ID            0
TEAM_W             0
TEAM_L             0
W_PCT              0
W_RANK             0
MVP_SHARE          0
dtype: int64

In [38]:
# save merged dataframe to a csv file
merged_df.to_csv('../data/processed/merged_df.csv')